### PR TITLE
Update based on feedback

### PR DESCRIPTION
**Pull request by Mooree003**
i'm not sure if this is addressing the feedback but this simplifies the title method

### CODE REVIEW

**Comment by a1831319** [comment]
Feedback being "Could we try retrieving the recipe title from one of the other elements on the page, and filtering out the pipe (|) and subsequent content from that? I think that would make for more readable recipe titles." - not 100% sure what they mean by this, but this does seem like a reasonable change. It may be a good idea to keep the recipe-title__mobile tag in the find though, makes it a bit more resilient to structure changes.

**Comment by Mooree003** [comment]
addressed

**Comment by heathrampazis** [comment]
looks good

**Comment by a1831319** [comment]
Seems fine to me. We'll probably end up with more feedback to address from the main PR either way, so I'm fine with this.

**Pull request merged**
